#!/bin/sh

# A git wrapper to add "@{u}" information to git describe
# output so that the build (labwc) version can have it.
# Works when the subdirectory where (patched) code is
# located at */with-labwc/wt-20yy-mm-dd-1234567[/*].

exec_git ()
{
        IFS=: # this setting does not affect expansion of "$@" (vs "$*")
        for d in $PATH
        do  test -x "$d"/git || continue
            test "$0" -ef "$d"/git || exec "$d"/git "$@"
        done
        echo 'Cannot find git(1)' >&2
        exit 1
}

test "$1" = describe || exec_git "$@"

set -euf

case $PWD in */with-labwc/wt-20??-??-??-u*) ;; *) exec_git "$@" ;; esac

u=${PWD##*/with-labwc/wt-20??-??-??-u}
u=${u%%/*}
test ${#u} = 7 || exec_git "$@"

s=`exec_git "$@"` || { ev=$?; test "%s" && echo "$s"; exit $ev; }

case $s in *-dirty) echo ${s%-dirty}-u$u-dirty ;; *) echo $s-u$u ;; esac
